import { MediumPost } from '../../shared/schema';
import { fetchRSSFeed } from './rss.js';

/**
 * Extracts Medium username from various URL formats
 * Supports: @username, medium.com/@username, medium.com/feed/@username
 * Returns null if no valid username is found.
 */
export function extractMediumUsername(input: string): string | null {
  // Remove whitespace
  input = input.trim();

  if (!input) {
    return null;
  }

  // Define valid username characters (alphanumeric, underscore, dot, hyphen)
  // This is an approximation of valid Medium usernames
  const usernameChars = '[\\w\\.\\-]+';

  // 1. Check if the input is JUST a username (with or without @)
  // This handles "username" and "@username"
  const exactMatchPattern = new RegExp(`^@?(${usernameChars})$`);
  const exactMatch = input.match(exactMatchPattern);
  if (exactMatch) {
    return `@${exactMatch[1]}`;
  }

  // 2. Try to extract from URL or text
  const urlPatterns = [
    /medium\.com\/@([\w\.\-]+)/,      // medium.com/@username
    /medium\.com\/feed\/@([\w\.\-]+)/, // medium.com/feed/@username
    /@([\w\.\-]+)/                    // @username anywhere in text
  ];

  for (const pattern of urlPatterns) {
    const match = input.match(pattern);
    if (match && match[1]) {
      return `@${match[1]}`;
    }
  }

  // If we reach here, we couldn't find a pattern and it wasn't a clean username
  return null;
}

/**
 * Constructs Medium RSS feed URL from username
 * @param username - Medium username (with or without @)
 * @returns RSS feed URL
 */
export function getMediumRSSUrl(username: string): string {
  const cleanUsername = username.startsWith('@') ? username.slice(1) : username;
  return `https://medium.com/feed/@${cleanUsername}`;
}

/**
 * Estimates reading time from content length (Medium's algorithm approximation)
 * Medium uses ~275 words per minute
 */
function estimateReadTime(content: string): number {
  const wordCount = content.split(/\s+/).length;
  const readTime = Math.ceil(wordCount / 275);
  return Math.max(1, readTime); // Minimum 1 minute
}

/**
 * Extracts claps count from Medium post (not available in RSS, returns null)
 * Note: Claps require scraping the actual post page, which we avoid for privacy
 */
function extractClaps(content: string): number | null {
  // Medium RSS doesn't include claps count
  // Would require scraping individual posts, which could log user data
  return null;
}

/**
 * Fetches Medium posts for a given username via RSS
 * Privacy: Uses public RSS feed, no authentication, no data logging
 * @param username - Medium username (with or without @)
 * @returns Array of MediumPost objects
 */
export async function getMediumPosts(username: string): Promise<MediumPost[]> {
  const feedUrl = getMediumRSSUrl(username);

  try {
    const feed = await fetchRSSFeed(feedUrl);

    return feed.items.map((item, index) => {
      const content = item.content || item.contentSnippet || '';
      const uniqueId = item.guid || item.link || `${feedUrl}-${index}`;
      const id = Buffer.from(uniqueId).toString('base64').substring(0, 32);

      return {
        id,
        title: item.title,
        description: item.contentSnippet?.substring(0, 200) || null,
        url: item.link,
        summary: null, // Will be generated by AI if selected
        selected: false,
        source: 'medium' as const,
        publishedAt: item.isoDate || item.pubDate || new Date().toISOString(),
        author: item.creator || username,
        tags: item.categories || [],
        claps: extractClaps(content),
        readTime: estimateReadTime(content)
      };
    });
  } catch (error) {
    // Don't log user data - only sanitized error
    throw new Error(`Failed to fetch Medium posts: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Validates a Medium username by checking if the RSS feed exists
 * @param username - Medium username to validate
 * @returns true if valid, false otherwise
 */
export async function validateMediumUsername(username: string): Promise<boolean> {
  try {
    const feedUrl = getMediumRSSUrl(username);
    await fetchRSSFeed(feedUrl);
    return true;
  } catch (error) {
    return false;
  }
}
