import Parser from 'rss-parser';
import { BlogPost } from '../../shared/schema';

const parser = new Parser({
  customFields: {
    item: [
      ['content:encoded', 'contentEncoded'],
      ['media:content', 'mediaContent']
    ]
  }
});

export interface RSSFeedItem {
  title: string;
  link: string;
  pubDate?: string;
  creator?: string;
  content?: string;
  contentSnippet?: string;
  guid?: string;
  categories?: string[];
  isoDate?: string;
}

export interface RSSFeed {
  title: string;
  description?: string;
  link: string;
  items: RSSFeedItem[];
}

/**
 * Fetches and parses an RSS feed from the given URL
 * Privacy: This function fetches data directly from user-provided URLs without logging
 * @param feedUrl - RSS feed URL provided by user
 * @returns Parsed RSS feed data
 */
export async function fetchRSSFeed(feedUrl: string): Promise<RSSFeed> {
  try {
    const feed = await parser.parseURL(feedUrl);

    return {
      title: feed.title || 'Untitled Feed',
      description: feed.description || undefined,
      link: feed.link || feedUrl,
      items: feed.items.map(item => ({
        title: item.title || 'Untitled',
        link: item.link || '',
        pubDate: item.pubDate,
        creator: item.creator || item.author,
        content: (item as any).contentEncoded || item.content,
        contentSnippet: item.contentSnippet,
        guid: item.guid || item.link,
        categories: item.categories || [],
        isoDate: item.isoDate
      }))
    };
  } catch (error) {
    // Don't log user data - only log sanitized error
    throw new Error(`Failed to fetch RSS feed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Converts RSS feed items to BlogPost schema format
 * Privacy: All processing happens in-memory, no data is stored
 * @param feedUrl - Original RSS feed URL
 * @param items - RSS feed items to convert
 * @param author - Optional author override
 * @returns Array of BlogPost objects
 */
export function convertRSSItemsToBlogPosts(
  feedUrl: string,
  items: RSSFeedItem[],
  author?: string
): BlogPost[] {
  return items.map((item, index) => {
    // Create a unique ID from the feed URL and item guid/link
    const uniqueId = item.guid || item.link || `${feedUrl}-${index}`;
    const id = Buffer.from(uniqueId).toString('base64').substring(0, 32);

    return {
      id,
      title: item.title,
      description: item.contentSnippet || item.content?.substring(0, 200) || null,
      url: item.link,
      summary: null, // Will be generated by AI if selected
      selected: false,
      source: 'blog_rss' as const,
      publishedAt: item.isoDate || item.pubDate || new Date().toISOString(),
      author: author || item.creator || null,
      tags: item.categories || [],
      feedUrl
    };
  });
}

/**
 * Fetches RSS feed and converts to BlogPost format
 * Privacy: No data logging, direct client-to-server processing only
 * @param feedUrl - RSS feed URL
 * @param author - Optional author name override
 * @returns Array of BlogPost objects ready for portfolio
 */
export async function getBlogPostsFromRSS(
  feedUrl: string,
  author?: string
): Promise<BlogPost[]> {
  const feed = await fetchRSSFeed(feedUrl);
  return convertRSSItemsToBlogPosts(feedUrl, feed.items, author);
}
