import Parser from 'rss-parser';
import { BlogPost } from '../../shared/schema';
import dns from 'dns';
import net from 'net';

// Check for private / local IP addresses to prevent SSRF
const isPrivateIP = (ip: string) => {
  const cleanIp = ip.replace(/^\[(.*)\]$/, '$1');
  if (!net.isIP(cleanIp)) return false;
  // Blocks loopback, private IPv4, unspecified, IPv6 loopback, and cloud metadata
  return /^(127\.|10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[0-1])\.|169\.254\.|0\.0\.0\.0|::1)/.test(cleanIp);
};

// Custom DNS lookup to prevent DNS rebinding attacks pointing to local IPs
const customLookup = (
  hostname: string,
  options: dns.LookupOptions | number,
  callback: (err: NodeJS.ErrnoException | null, address: string | dns.LookupAddress[], family: number) => void
) => {
  dns.lookup(hostname, options as dns.LookupOptions, (err, address, family) => {
    if (err) return callback(err, address, family);

    const addresses = Array.isArray(address) ? address : [{ address }];
    for (const addr of addresses) {
      if (isPrivateIP(addr.address)) {
        return callback(new Error(`Access to private IP ${addr.address} is blocked`), address, family);
      }
    }
    callback(err, address, family);
  });
};

const parser = new Parser({
  maxRedirects: 0, // Prevent redirects to IP literals to bypass dns.lookup
  requestOptions: {
    lookup: customLookup
  },
  customFields: {
    item: [
      ['content:encoded', 'contentEncoded'],
      ['media:content', 'mediaContent']
    ]
  }
});

export interface RSSFeedItem {
  title: string;
  link: string;
  pubDate?: string;
  creator?: string;
  content?: string;
  contentSnippet?: string;
  guid?: string;
  categories?: string[];
  isoDate?: string;
}

export interface RSSFeed {
  title: string;
  description?: string;
  link: string;
  items: RSSFeedItem[];
}

/**
 * Fetches and parses an RSS feed from the given URL
 * Privacy: This function fetches data directly from user-provided URLs without logging
 * @param feedUrl - RSS feed URL provided by user
 * @returns Parsed RSS feed data
 */
export async function fetchRSSFeed(feedUrl: string): Promise<RSSFeed> {
  try {
    // Pre-flight check: prevent direct IP access to private network
    const url = new URL(feedUrl);
    if (isPrivateIP(url.hostname)) {
      throw new Error(`Direct access to private network is blocked`);
    }

    const feed = await parser.parseURL(feedUrl);

    return {
      title: feed.title || 'Untitled Feed',
      description: feed.description || undefined,
      link: feed.link || feedUrl,
      items: feed.items.map(item => ({
        title: item.title || 'Untitled',
        link: item.link || '',
        pubDate: item.pubDate,
        creator: item.creator || (item as any).author,
        content: (item as any).contentEncoded || item.content,
        contentSnippet: item.contentSnippet,
        guid: item.guid || item.link,
        categories: item.categories || [],
        isoDate: item.isoDate
      }))
    };
  } catch (error) {
    // Don't log user data - only log sanitized error
    throw new Error(`Failed to fetch RSS feed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Converts RSS feed items to BlogPost schema format
 * Privacy: All processing happens in-memory, no data is stored
 * @param feedUrl - Original RSS feed URL
 * @param items - RSS feed items to convert
 * @param author - Optional author override
 * @returns Array of BlogPost objects
 */
export function convertRSSItemsToBlogPosts(
  feedUrl: string,
  items: RSSFeedItem[],
  author?: string
): BlogPost[] {
  return items.map((item, index) => {
    // Create a unique ID from the feed URL and item guid/link
    const uniqueId = item.guid || item.link || `${feedUrl}-${index}`;
    const id = Buffer.from(uniqueId).toString('base64').substring(0, 32);

    return {
      id,
      title: item.title,
      description: item.contentSnippet || item.content?.substring(0, 200) || null,
      url: item.link,
      summary: null, // Will be generated by AI if selected
      selected: false,
      source: 'blog_rss' as const,
      publishedAt: item.isoDate || item.pubDate || new Date().toISOString(),
      author: author || item.creator || null,
      tags: item.categories || [],
      feedUrl
    };
  });
}

/**
 * Fetches RSS feed and converts to BlogPost format
 * Privacy: No data logging, direct client-to-server processing only
 * @param feedUrl - RSS feed URL
 * @param author - Optional author name override
 * @returns Array of BlogPost objects ready for portfolio
 */
export async function getBlogPostsFromRSS(
  feedUrl: string,
  author?: string
): Promise<BlogPost[]> {
  const feed = await fetchRSSFeed(feedUrl);
  return convertRSSItemsToBlogPosts(feedUrl, feed.items, author);
}
